import type { WorkItem } from "@skrivebord/contracts";

export type Booking = { id:string; workspaceId:string; propertyId:string; guestDisplayName:string; checkInAt:string; checkOutAt:string; status:"ACTIVE"|"CANCELLED"|"COMPLETED" };
export type CalendarEvent = { id:string; workspaceId:string; propertyId?:string; bookingId?:string; title:string; startsAt:string; endsAt:string; startLabel:string; categoryLabel:string; sourceLabel:string };
export type YearPlanItem = { id:string; workspaceId:string; propertyId?:string; title:string; description:string; month:number; windowStartDay:number; windowEndDay:number; windowLabel:string; active:boolean };
export type ActivityItem = { id:string; timeLabel:string; summary:string; detail?:string };
export type OperationalSnapshot = { workspaceId:string; bookings:Booking[]; calendarEvents:CalendarEvent[]; yearPlanItems:YearPlanItem[]; activity:ActivityItem[]; connectorHealthy:boolean };

export function bookingsOverlap(a:Booking,b:Booking):boolean { if(a.propertyId!==b.propertyId||a.status!=="ACTIVE"||b.status!=="ACTIVE") return false; return new Date(a.checkInAt).getTime()<new Date(b.checkOutAt).getTime()&&new Date(b.checkInAt).getTime()<new Date(a.checkOutAt).getTime(); }
export function findBookingConflicts(bookings:Booking[]):Array<[Booking,Booking]>{ const conflicts:Array<[Booking,Booking]>=[]; for(let i=0;i<bookings.length;i+=1){for(let j=i+1;j<bookings.length;j+=1){const a=bookings[i];const b=bookings[j];if(a&&b&&bookingsOverlap(a,b)) conflicts.push([a,b]);}} return conflicts; }
function localDay(date:Date):{month:number;day:number}{const fmt=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Copenhagen",month:"numeric",day:"numeric"});const parts=fmt.formatToParts(date);return {month:Number(parts.find((p)=>p.type==="month")?.value),day:Number(parts.find((p)=>p.type==="day")?.value)};}
export function yearPlanWindowOpen(item:YearPlanItem,now:Date):boolean{if(!item.active)return false;const {month,day}=localDay(now);return month===item.month&&day>=item.windowStartDay&&day<=item.windowEndDay;}

export function buildTodayView(snapshot:OperationalSnapshot,now:Date):{requiresYou:WorkItem[];today:WorkItem[];upcoming:WorkItem[];thisMonth:WorkItem[]}{
 const requiresYou:WorkItem[]=[];const today:WorkItem[]=[];const upcoming:WorkItem[]=[];const thisMonth:WorkItem[]=[];
 for(const[a,b]of findBookingConflicts(snapshot.bookings)){requiresYou.push({id:`conflict:${a.id}:${b.id}`,workspaceId:snapshot.workspaceId,kind:"BOOKING_CONFLICT",title:"To bookinger overlapper",reason:`${a.guestDisplayName} og ${b.guestDisplayName} overlapper på samme ejendom.`,priorityClass:"REQUIRES_YOU",timingLabel:"Skal afklares før næste ankomst",evidence:[{kind:"BOOKING",id:a.id,label:a.guestDisplayName},{kind:"BOOKING",id:b.id,label:b.guestDisplayName}],recommendedActionId:"booking.resolve_conflict",recommendedActionLabel:"Gennemgå konflikt",agentExecutionMode:"HUMAN_ONLY",attentionType:"CONFLICT"});}
 if(!snapshot.connectorHealthy){requiresYou.push({id:"connector:google:expired",workspaceId:snapshot.workspaceId,kind:"CONNECTOR_ACCESS",title:"Google Calendar skal forbindes igen",reason:"Forbindelsen er udløbet. Eksisterende data er bevaret, men nye ændringer kan ikke hentes.",priorityClass:"REQUIRES_YOU",evidence:[{kind:"CONNECTOR_STATE",label:"Google Calendar · AUTH_EXPIRED"}],recommendedActionId:"connection.reconnect",recommendedActionLabel:"Forbind igen",agentExecutionMode:"HUMAN_ONLY",attentionType:"ACCESS"});}
 for(const booking of snapshot.bookings.filter((b)=>b.status==="ACTIVE")){const hoursUntil=(new Date(booking.checkInAt).getTime()-now.getTime())/3600000;if(hoursUntil>=0&&hoursUntil<=72){today.push({id:`arrival:${booking.id}`,workspaceId:snapshot.workspaceId,kind:"GUEST_ARRIVAL_INFO",title:`Klargør ankomstinfo til ${booking.guestDisplayName}`,reason:"Gæsten ankommer inden for tre dage, og der er endnu ikke registreret afsendt ankomstinformation.",priorityClass:"TODAY",timingLabel:new Intl.DateTimeFormat("da-DK",{timeZone:"Europe/Copenhagen",weekday:"long",hour:"2-digit",minute:"2-digit"}).format(new Date(booking.checkInAt)),evidence:[{kind:"BOOKING",id:booking.id,label:`Booking · ${booking.guestDisplayName}`},{kind:"RULE",label:"rental.arrival_info"}],recommendedActionId:"guest_message.draft",recommendedActionLabel:"Klargør besked",agentExecutionMode:"REVIEW"});}}
 for(const item of snapshot.yearPlanItems){const work:WorkItem={id:`yearplan:${item.id}`,workspaceId:snapshot.workspaceId,kind:"YEAR_PLAN",title:item.title,reason:item.description,priorityClass:yearPlanWindowOpen(item,now)?"TODAY":"UPCOMING",timingLabel:item.windowLabel,evidence:[{kind:"YEAR_PLAN",id:item.id,label:item.title}],recommendedActionId:"yearplan.complete",recommendedActionLabel:"Åbn aktivitet",agentExecutionMode:"AUTO"};const {month}=localDay(now);if(item.month===month)thisMonth.push(work);if(yearPlanWindowOpen(item,now))today.push(work);else if(item.month>=month)upcoming.push(work);}
 return {requiresYou,today,upcoming:upcoming.slice(0,6),thisMonth};
}

export function buildAlsLebenSnapshot():OperationalSnapshot{return {workspaceId:"ws_alsleben",connectorHealthy:false,bookings:[{id:"b_184",workspaceId:"ws_alsleben",propertyId:"p_havn",guestDisplayName:"Anna Jensen",checkInAt:"2026-09-24T15:00:00+02:00",checkOutAt:"2026-09-28T11:00:00+02:00",status:"ACTIVE"},{id:"b_185",workspaceId:"ws_alsleben",propertyId:"p_havn",guestDisplayName:"Martin Holm",checkInAt:"2026-09-27T15:00:00+02:00",checkOutAt:"2026-09-30T11:00:00+02:00",status:"ACTIVE"},{id:"b_186",workspaceId:"ws_alsleben",propertyId:"p_skov",guestDisplayName:"Sara Lund",checkInAt:"2026-09-29T15:00:00+02:00",checkOutAt:"2026-10-03T11:00:00+02:00",status:"ACTIVE"}],calendarEvents:[{id:"e_clean",workspaceId:"ws_alsleben",propertyId:"p_havn",title:"Rengøring · Havnehuset",startsAt:"2026-09-24T10:00:00+02:00",endsAt:"2026-09-24T12:00:00+02:00",startLabel:"Tor 24/9 · 10:00",categoryLabel:"Rengøring",sourceLabel:"Google"},{id:"e_arrival",workspaceId:"ws_alsleben",propertyId:"p_havn",bookingId:"b_184",title:"Anna Jensen ankommer",startsAt:"2026-09-24T15:00:00+02:00",endsAt:"2026-09-24T16:00:00+02:00",startLabel:"Tor 24/9 · 15:00",categoryLabel:"Booking",sourceLabel:"Booking"},{id:"e_maint",workspaceId:"ws_alsleben",propertyId:"p_skov",title:"Service på varmepumpe",startsAt:"2026-09-25T09:00:00+02:00",endsAt:"2026-09-25T11:00:00+02:00",startLabel:"Fre 25/9 · 09:00",categoryLabel:"Vedligehold",sourceLabel:"Lene"}],yearPlanItems:[{id:"yp_terrace",workspaceId:"ws_alsleben",propertyId:"p_havn",title:"Vinterklargør terrasse",description:"Terrassen skal gennemgås og klargøres før efterårsvejret.",month:9,windowStartDay:15,windowEndDay:30,windowLabel:"15.–30. september",active:true}],activity:[{id:"a1",timeLabel:"14:32",summary:"Mojn flyttede rengøring til fredag",detail:"Godkendt af Lene"},{id:"a2",timeLabel:"13:18",summary:"Mojn klargjorde ankomstinformation",detail:"Booking #184"},{id:"a3",timeLabel:"11:04",summary:"Lene ændrede check-in til 15:00"},{id:"a4",timeLabel:"09:22",summary:"Google Calendar synkroniserede"}]};}
