import { buildAlsLebenSnapshot, buildTodayView } from "@skrivebord/domain";
import { ArrowRight, CircleAlert, Clock3 } from "lucide-react";
import { PageTitle } from "../_components/page-title";

function WorkRow({ title, reason, timing, action }: { title: string; reason: string; timing?: string; action: string }) {
  return <div className="grid gap-3 border-t border-[var(--border-default)] py-5 first:border-t-0 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="font-medium">{title}</div><div className="mt-1 text-sm leading-6 text-[var(--text-secondary)]">{reason}</div>{timing ? <div className="mt-2 flex items-center gap-1.5 text-xs text-[var(--text-muted)]"><Clock3 size={14}/>{timing}</div> : null}</div><button className="inline-flex items-center gap-2 justify-self-start rounded-md border border-[var(--border-strong)] bg-white px-3 py-2 text-sm font-semibold hover:bg-[var(--surface-muted)] sm:justify-self-end">{action}<ArrowRight size={15}/></button></div>;
}

export default function TodayPage() {
  const view = buildTodayView(buildAlsLebenSnapshot(), new Date("2026-09-22T08:00:00+02:00"));
  return <><PageTitle title="I dag" subtitle="Tirsdag 22. september · Et lille, begrundet overblik over det der faktisk kræver handling."/>{view.requiresYou.length > 0 ? <section className="mb-10" aria-labelledby="requires-you"><div className="mb-3 flex items-center gap-2"><CircleAlert size={18} aria-hidden="true"/><h2 id="requires-you" className="text-lg font-semibold">Kræver dig</h2><span className="text-sm text-[var(--text-muted)]">{view.requiresYou.length}</span></div><div className="border-y border-[var(--border-default)]">{view.requiresYou.map((item) => <WorkRow key={item.id} title={item.title} reason={item.reason} timing={item.timingLabel} action={item.recommendedActionLabel}/>)}</div></section> : null}<section className="mb-10" aria-labelledby="today-work"><h2 id="today-work" className="mb-3 text-lg font-semibold">Bør gøres i dag</h2><div className="border-y border-[var(--border-default)]">{view.today.map((item) => <WorkRow key={item.id} title={item.title} reason={item.reason} timing={item.timingLabel} action={item.recommendedActionLabel}/>)}</div></section><div className="grid gap-8 lg:grid-cols-2"><section><h2 className="mb-3 text-lg font-semibold">Næste 7 dage</h2><div className="border-t border-[var(--border-default)]">{view.upcoming.map((item) => <div key={item.id} className="border-b border-[var(--border-default)] py-4"><div className="font-medium">{item.title}</div><div className="mt-1 text-sm text-[var(--text-secondary)]">{item.reason}</div></div>)}</div></section><section><h2 className="mb-3 text-lg font-semibold">Denne måned</h2><div className="border-t border-[var(--border-default)]">{view.thisMonth.map((item) => <div key={item.id} className="border-b border-[var(--border-default)] py-4"><div className="font-medium">{item.title}</div><div className="mt-1 text-sm text-[var(--text-secondary)]">{item.reason}</div></div>)}</div></section></div></>;
}
